/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppHostsRouteImport } from './routes/app/hosts'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppSettingsRouteRouteImport } from './routes/app/settings/route'
import { Route as AppTestsIndexRouteImport } from './routes/app/tests/index'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppTestsNewRouteImport } from './routes/app/tests/new'
import { Route as AppTestsTestIdRouteImport } from './routes/app/tests/$testId'
import { Route as AppSettingsSecurityRouteImport } from './routes/app/settings/security'
import { Route as AppSettingsAppearanceRouteImport } from './routes/app/settings/appearance'
import { Route as AppSettingsAccountRouteImport } from './routes/app/settings/account'
import { Route as AppTestsTestIdIndexRouteImport } from './routes/app/tests/$testId/index'
import { Route as AppSettingsOrganizationIndexRouteImport } from './routes/app/settings/organization/index'
import { Route as AppSettingsOrganizationMembersRouteImport } from './routes/app/settings/organization/members'
import { Route as AppSettingsOrganizationInvitationsRouteImport } from './routes/app/settings/organization/invitations'
import { Route as AppTestsTestIdResultsResultIdRouteImport } from './routes/app/tests/$testId/results/$resultId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHostsRoute = AppHostsRouteImport.update({
  id: '/hosts',
  path: '/hosts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTestsIndexRoute = AppTestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppTestsNewRoute = AppTestsNewRouteImport.update({
  id: '/tests/new',
  path: '/tests/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTestsTestIdRoute = AppTestsTestIdRouteImport.update({
  id: '/tests/$testId',
  path: '/tests/$testId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsAppearanceRoute = AppSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppTestsTestIdIndexRoute = AppTestsTestIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTestsTestIdRoute,
} as any)
const AppSettingsOrganizationIndexRoute =
  AppSettingsOrganizationIndexRouteImport.update({
    id: '/organization/',
    path: '/organization/',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppSettingsOrganizationMembersRoute =
  AppSettingsOrganizationMembersRouteImport.update({
    id: '/organization/members',
    path: '/organization/members',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppSettingsOrganizationInvitationsRoute =
  AppSettingsOrganizationInvitationsRouteImport.update({
    id: '/organization/invitations',
    path: '/organization/invitations',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppTestsTestIdResultsResultIdRoute =
  AppTestsTestIdResultsResultIdRouteImport.update({
    id: '/results/$resultId',
    path: '/results/$resultId',
    getParentRoute: () => AppTestsTestIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/settings': typeof AppSettingsRouteRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/hosts': typeof AppHostsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/app/': typeof AppIndexRoute
  '/app/settings/account': typeof AppSettingsAccountRoute
  '/app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/tests/$testId': typeof AppTestsTestIdRouteWithChildren
  '/app/tests/new': typeof AppTestsNewRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/tests/': typeof AppTestsIndexRoute
  '/app/settings/organization/invitations': typeof AppSettingsOrganizationInvitationsRoute
  '/app/settings/organization/members': typeof AppSettingsOrganizationMembersRoute
  '/app/settings/organization/': typeof AppSettingsOrganizationIndexRoute
  '/app/tests/$testId/': typeof AppTestsTestIdIndexRoute
  '/app/tests/$testId/results/$resultId': typeof AppTestsTestIdResultsResultIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/hosts': typeof AppHostsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/app': typeof AppIndexRoute
  '/app/settings/account': typeof AppSettingsAccountRoute
  '/app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/tests/new': typeof AppTestsNewRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/tests': typeof AppTestsIndexRoute
  '/app/settings/organization/invitations': typeof AppSettingsOrganizationInvitationsRoute
  '/app/settings/organization/members': typeof AppSettingsOrganizationMembersRoute
  '/app/settings/organization': typeof AppSettingsOrganizationIndexRoute
  '/app/tests/$testId': typeof AppTestsTestIdIndexRoute
  '/app/tests/$testId/results/$resultId': typeof AppTestsTestIdResultsResultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/settings': typeof AppSettingsRouteRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/hosts': typeof AppHostsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/app/': typeof AppIndexRoute
  '/app/settings/account': typeof AppSettingsAccountRoute
  '/app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/tests/$testId': typeof AppTestsTestIdRouteWithChildren
  '/app/tests/new': typeof AppTestsNewRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/tests/': typeof AppTestsIndexRoute
  '/app/settings/organization/invitations': typeof AppSettingsOrganizationInvitationsRoute
  '/app/settings/organization/members': typeof AppSettingsOrganizationMembersRoute
  '/app/settings/organization/': typeof AppSettingsOrganizationIndexRoute
  '/app/tests/$testId/': typeof AppTestsTestIdIndexRoute
  '/app/tests/$testId/results/$resultId': typeof AppTestsTestIdResultsResultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/app/settings'
    | '/app/dashboard'
    | '/app/hosts'
    | '/app/onboarding'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/app/'
    | '/app/settings/account'
    | '/app/settings/appearance'
    | '/app/settings/security'
    | '/app/tests/$testId'
    | '/app/tests/new'
    | '/app/settings/'
    | '/app/tests/'
    | '/app/settings/organization/invitations'
    | '/app/settings/organization/members'
    | '/app/settings/organization/'
    | '/app/tests/$testId/'
    | '/app/tests/$testId/results/$resultId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/app/dashboard'
    | '/app/hosts'
    | '/app/onboarding'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/app'
    | '/app/settings/account'
    | '/app/settings/appearance'
    | '/app/settings/security'
    | '/app/tests/new'
    | '/app/settings'
    | '/app/tests'
    | '/app/settings/organization/invitations'
    | '/app/settings/organization/members'
    | '/app/settings/organization'
    | '/app/tests/$testId'
    | '/app/tests/$testId/results/$resultId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/app/settings'
    | '/app/dashboard'
    | '/app/hosts'
    | '/app/onboarding'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/app/'
    | '/app/settings/account'
    | '/app/settings/appearance'
    | '/app/settings/security'
    | '/app/tests/$testId'
    | '/app/tests/new'
    | '/app/settings/'
    | '/app/tests/'
    | '/app/settings/organization/invitations'
    | '/app/settings/organization/members'
    | '/app/settings/organization/'
    | '/app/tests/$testId/'
    | '/app/tests/$testId/results/$resultId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/hosts': {
      id: '/app/hosts'
      path: '/hosts'
      fullPath: '/app/hosts'
      preLoaderRoute: typeof AppHostsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/tests/': {
      id: '/app/tests/'
      path: '/tests'
      fullPath: '/app/tests/'
      preLoaderRoute: typeof AppTestsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/tests/new': {
      id: '/app/tests/new'
      path: '/tests/new'
      fullPath: '/app/tests/new'
      preLoaderRoute: typeof AppTestsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/tests/$testId': {
      id: '/app/tests/$testId'
      path: '/tests/$testId'
      fullPath: '/app/tests/$testId'
      preLoaderRoute: typeof AppTestsTestIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/security': {
      id: '/app/settings/security'
      path: '/security'
      fullPath: '/app/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/settings/appearance': {
      id: '/app/settings/appearance'
      path: '/appearance'
      fullPath: '/app/settings/appearance'
      preLoaderRoute: typeof AppSettingsAppearanceRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/settings/account': {
      id: '/app/settings/account'
      path: '/account'
      fullPath: '/app/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/tests/$testId/': {
      id: '/app/tests/$testId/'
      path: '/'
      fullPath: '/app/tests/$testId/'
      preLoaderRoute: typeof AppTestsTestIdIndexRouteImport
      parentRoute: typeof AppTestsTestIdRoute
    }
    '/app/settings/organization/': {
      id: '/app/settings/organization/'
      path: '/organization'
      fullPath: '/app/settings/organization/'
      preLoaderRoute: typeof AppSettingsOrganizationIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/settings/organization/members': {
      id: '/app/settings/organization/members'
      path: '/organization/members'
      fullPath: '/app/settings/organization/members'
      preLoaderRoute: typeof AppSettingsOrganizationMembersRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/settings/organization/invitations': {
      id: '/app/settings/organization/invitations'
      path: '/organization/invitations'
      fullPath: '/app/settings/organization/invitations'
      preLoaderRoute: typeof AppSettingsOrganizationInvitationsRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/tests/$testId/results/$resultId': {
      id: '/app/tests/$testId/results/$resultId'
      path: '/results/$resultId'
      fullPath: '/app/tests/$testId/results/$resultId'
      preLoaderRoute: typeof AppTestsTestIdResultsResultIdRouteImport
      parentRoute: typeof AppTestsTestIdRoute
    }
  }
}

interface AppSettingsRouteRouteChildren {
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsAppearanceRoute: typeof AppSettingsAppearanceRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSettingsOrganizationInvitationsRoute: typeof AppSettingsOrganizationInvitationsRoute
  AppSettingsOrganizationMembersRoute: typeof AppSettingsOrganizationMembersRoute
  AppSettingsOrganizationIndexRoute: typeof AppSettingsOrganizationIndexRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsAppearanceRoute: AppSettingsAppearanceRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSettingsOrganizationInvitationsRoute:
    AppSettingsOrganizationInvitationsRoute,
  AppSettingsOrganizationMembersRoute: AppSettingsOrganizationMembersRoute,
  AppSettingsOrganizationIndexRoute: AppSettingsOrganizationIndexRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppTestsTestIdRouteChildren {
  AppTestsTestIdIndexRoute: typeof AppTestsTestIdIndexRoute
  AppTestsTestIdResultsResultIdRoute: typeof AppTestsTestIdResultsResultIdRoute
}

const AppTestsTestIdRouteChildren: AppTestsTestIdRouteChildren = {
  AppTestsTestIdIndexRoute: AppTestsTestIdIndexRoute,
  AppTestsTestIdResultsResultIdRoute: AppTestsTestIdResultsResultIdRoute,
}

const AppTestsTestIdRouteWithChildren = AppTestsTestIdRoute._addFileChildren(
  AppTestsTestIdRouteChildren,
)

interface AppRouteRouteChildren {
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppHostsRoute: typeof AppHostsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTestsTestIdRoute: typeof AppTestsTestIdRouteWithChildren
  AppTestsNewRoute: typeof AppTestsNewRoute
  AppTestsIndexRoute: typeof AppTestsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppHostsRoute: AppHostsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppIndexRoute: AppIndexRoute,
  AppTestsTestIdRoute: AppTestsTestIdRouteWithChildren,
  AppTestsNewRoute: AppTestsNewRoute,
  AppTestsIndexRoute: AppTestsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
