/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppHostsRouteImport } from './routes/app/hosts'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppTestsIndexRouteImport } from './routes/app/tests/index'
import { Route as AppTestsNewRouteImport } from './routes/app/tests/new'
import { Route as AppTestsTestIdRouteImport } from './routes/app/tests/$testId'
import { Route as AppTestsTestIdIndexRouteImport } from './routes/app/tests/$testId/index'
import { Route as AppTestsTestIdResultsResultIdRouteImport } from './routes/app/tests/$testId/results/$resultId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHostsRoute = AppHostsRouteImport.update({
  id: '/hosts',
  path: '/hosts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTestsIndexRoute = AppTestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTestsNewRoute = AppTestsNewRouteImport.update({
  id: '/tests/new',
  path: '/tests/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTestsTestIdRoute = AppTestsTestIdRouteImport.update({
  id: '/tests/$testId',
  path: '/tests/$testId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTestsTestIdIndexRoute = AppTestsTestIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTestsTestIdRoute,
} as any)
const AppTestsTestIdResultsResultIdRoute =
  AppTestsTestIdResultsResultIdRouteImport.update({
    id: '/results/$resultId',
    path: '/results/$resultId',
    getParentRoute: () => AppTestsTestIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/hosts': typeof AppHostsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/': typeof AppIndexRoute
  '/app/tests/$testId': typeof AppTestsTestIdRouteWithChildren
  '/app/tests/new': typeof AppTestsNewRoute
  '/app/tests/': typeof AppTestsIndexRoute
  '/app/tests/$testId/': typeof AppTestsTestIdIndexRoute
  '/app/tests/$testId/results/$resultId': typeof AppTestsTestIdResultsResultIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/hosts': typeof AppHostsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app': typeof AppIndexRoute
  '/app/tests/new': typeof AppTestsNewRoute
  '/app/tests': typeof AppTestsIndexRoute
  '/app/tests/$testId': typeof AppTestsTestIdIndexRoute
  '/app/tests/$testId/results/$resultId': typeof AppTestsTestIdResultsResultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/hosts': typeof AppHostsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/': typeof AppIndexRoute
  '/app/tests/$testId': typeof AppTestsTestIdRouteWithChildren
  '/app/tests/new': typeof AppTestsNewRoute
  '/app/tests/': typeof AppTestsIndexRoute
  '/app/tests/$testId/': typeof AppTestsTestIdIndexRoute
  '/app/tests/$testId/results/$resultId': typeof AppTestsTestIdResultsResultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/app/dashboard'
    | '/app/hosts'
    | '/app/onboarding'
    | '/app/'
    | '/app/tests/$testId'
    | '/app/tests/new'
    | '/app/tests/'
    | '/app/tests/$testId/'
    | '/app/tests/$testId/results/$resultId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/app/dashboard'
    | '/app/hosts'
    | '/app/onboarding'
    | '/app'
    | '/app/tests/new'
    | '/app/tests'
    | '/app/tests/$testId'
    | '/app/tests/$testId/results/$resultId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/app/dashboard'
    | '/app/hosts'
    | '/app/onboarding'
    | '/app/'
    | '/app/tests/$testId'
    | '/app/tests/new'
    | '/app/tests/'
    | '/app/tests/$testId/'
    | '/app/tests/$testId/results/$resultId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/hosts': {
      id: '/app/hosts'
      path: '/hosts'
      fullPath: '/app/hosts'
      preLoaderRoute: typeof AppHostsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/tests/': {
      id: '/app/tests/'
      path: '/tests'
      fullPath: '/app/tests/'
      preLoaderRoute: typeof AppTestsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/tests/new': {
      id: '/app/tests/new'
      path: '/tests/new'
      fullPath: '/app/tests/new'
      preLoaderRoute: typeof AppTestsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/tests/$testId': {
      id: '/app/tests/$testId'
      path: '/tests/$testId'
      fullPath: '/app/tests/$testId'
      preLoaderRoute: typeof AppTestsTestIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/tests/$testId/': {
      id: '/app/tests/$testId/'
      path: '/'
      fullPath: '/app/tests/$testId/'
      preLoaderRoute: typeof AppTestsTestIdIndexRouteImport
      parentRoute: typeof AppTestsTestIdRoute
    }
    '/app/tests/$testId/results/$resultId': {
      id: '/app/tests/$testId/results/$resultId'
      path: '/results/$resultId'
      fullPath: '/app/tests/$testId/results/$resultId'
      preLoaderRoute: typeof AppTestsTestIdResultsResultIdRouteImport
      parentRoute: typeof AppTestsTestIdRoute
    }
  }
}

interface AppTestsTestIdRouteChildren {
  AppTestsTestIdIndexRoute: typeof AppTestsTestIdIndexRoute
  AppTestsTestIdResultsResultIdRoute: typeof AppTestsTestIdResultsResultIdRoute
}

const AppTestsTestIdRouteChildren: AppTestsTestIdRouteChildren = {
  AppTestsTestIdIndexRoute: AppTestsTestIdIndexRoute,
  AppTestsTestIdResultsResultIdRoute: AppTestsTestIdResultsResultIdRoute,
}

const AppTestsTestIdRouteWithChildren = AppTestsTestIdRoute._addFileChildren(
  AppTestsTestIdRouteChildren,
)

interface AppRouteRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppHostsRoute: typeof AppHostsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTestsTestIdRoute: typeof AppTestsTestIdRouteWithChildren
  AppTestsNewRoute: typeof AppTestsNewRoute
  AppTestsIndexRoute: typeof AppTestsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppHostsRoute: AppHostsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppIndexRoute: AppIndexRoute,
  AppTestsTestIdRoute: AppTestsTestIdRouteWithChildren,
  AppTestsNewRoute: AppTestsNewRoute,
  AppTestsIndexRoute: AppTestsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
